<?php

namespace Tests\Traits;

trait FakeXmlTrait
{
    protected function getXml(): string
    {
        return <<<XML
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:media="http://search.yahoo.com/mrss/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/">
	<channel>
		<title><![CDATA[Ziņas]]></title>
		<link>https://www.delfi.lv</link>
		<description><![CDATA[Jaunākās ziņas]]></description>
		<language>lv</language>
		<copyright>A/S DELFI, 2023. All rights reserved.</copyright>
		<lastBuildDate>Fri, 18 Aug 2023 17:34:16 +0300</lastBuildDate>
		<generator>AS Delfi, https://www.delfi.lv/</generator>
		<image>
			<url>http://g.delfi.lv/d/i/rss/230x139_DELFI_logo.png</url>
			<link>https://www.delfi.lv</link>
			<title><![CDATA[Ziņas]]></title>
		</image>
		<atom:link href="https://www.delfi.lv/rss?channel=delfi" rel="self" type="application/rss+xml" />
        <item><title><![CDATA[Purvciemā ugunsgrēkā piektdien dzīvību zaudējuši divi mazi bērni]]></title><category>Sabiedrība</category><enclosure url="http://g.delfi.lv/images/pix/420x0/3J4n4Kv8YqM/rotallieta-lacitis-netirs-bailes-vardarbiba-pret-berniem-49167163.jpg" type="image/png" /><link>https://www.delfi.lv/news/national/politics/purvciema-ugunsgreka-piektdien-dzivibu-zaudejusi-divi-mazi-berni.d?id=55859356</link><guid>https://www.delfi.lv/news/national/politics/purvciema-ugunsgreka-piektdien-dzivibu-zaudejusi-divi-mazi-berni.d?id=55859356</guid><description><![CDATA[Rīgā, Purvciemā, Ieriķu ielā piektdienas pēcpusdienā ugunsgrēkā gājuši bojā divi pirmskolas vecuma bērni, informēja atbildīgajos dienestos.]]></description><media:content url="http://g.delfi.lv/images/pix/420x0/3J4n4Kv8YqM/rotallieta-lacitis-netirs-bailes-vardarbiba-pret-berniem-49167163.jpg" /><slash:comments>0</slash:comments><pubDate>Fri, 18 Aug 2023 17:29:56 +0300</pubDate></item>
        <item><title><![CDATA[Kuleba: 'Ukrainas stratēģija ir atbrīvot Āfriku no Krievijas tvēriena']]></title><category>Ārzemēs</category><enclosure url="http://g.delfi.lv/images/pix/420x0/oa6lRRYwJd0/kuleba-54036706.jpg" type="image/png" /><link>https://www.delfi.lv/news/arzemes/kuleba-ukrainas-strategija-ir-atbrivot-afriku-no-krievijas-tveriena.d?id=55859332</link><guid>https://www.delfi.lv/news/arzemes/kuleba-ukrainas-strategija-ir-atbrivot-afriku-no-krievijas-tveriena.d?id=55859332</guid><description><![CDATA[Kijiva plāno ieguldīt ievērojamu politisko kapitālu, lai uzlabotu attiecības ar Āfrikas valstīm, atsaucoties uz Ukrainas ārlietu ministra Dmitro Kulebas teikto, vēsta medijs &quot;Al Jazeera&quot;.]]></description><media:content url="http://g.delfi.lv/images/pix/420x0/oa6lRRYwJd0/kuleba-54036706.jpg" /><slash:comments>0</slash:comments><pubDate>Fri, 18 Aug 2023 17:25:33 +0300</pubDate></item>
        <item><title><![CDATA[Intervija ar ministru prezidentes amata kandidāti Eviku Siliņu]]></title><category>Kāpēc</category><enclosure url="http://g.delfi.lv/images/pix/420x0/i_5larerhpc/kapec-podkasts-54096364.jpg" type="image/png" /><link>https://www.delfi.lv/podkasti/kapec/intervija-ar-ministru-prezidentes-amata-kandidati-eviku-silinu.d?id=55859226</link><guid>https://www.delfi.lv/podkasti/kapec/intervija-ar-ministru-prezidentes-amata-kandidati-eviku-silinu.d?id=55859226</guid><description><![CDATA[Līdzšinējam ministru prezidentam Krišjānim Kariņam (JV) atkāpjoties no amata, &quot;Jaunā Vienotība&quot; (JV) kā nākamo šī amata kandidāti izvirzījusi pašreizējo labklājības ministri Eviku Siliņu. Kā politiķe Kā Siliņa veidos un vadīs jauno valdību – par to &quot;Delfi TV&quot; raidījumā &quot;Kāpēc&quot; ar Siliņu sarunājās žurnāliste Olga Dragiļeva.]]></description><media:content url="http://g.delfi.lv/images/pix/420x0/i_5larerhpc/kapec-podkasts-54096364.jpg" /><slash:comments>0</slash:comments><pubDate>Fri, 18 Aug 2023 16:52:13 +0300</pubDate></item>
        <item><title><![CDATA[Vairums vāciešu nav apmierināts ar Šolcu, liecina aptauja]]></title><category>Ārzemēs</category><enclosure url="http://g.delfi.lv/images/pix/420x0/xsbuTYOQmys/solcs-54444000.jpg" type="image/png" /><link>https://www.delfi.lv/news/arzemes/vairums-vaciesu-nav-apmierinats-ar-solcu-liecina-aptauja.d?id=55859148</link><guid>https://www.delfi.lv/news/arzemes/vairums-vaciesu-nav-apmierinats-ar-solcu-liecina-aptauja.d?id=55859148</guid><description><![CDATA[Vairums vāciešu nav apmierināts ar kancleru Olafu Šolcu un viņa vadīto trīs partiju koalīciju, liecina piektdien publicētie aptaujas rezultāti.]]></description><media:content url="http://g.delfi.lv/images/pix/420x0/xsbuTYOQmys/solcs-54444000.jpg" /><slash:comments>0</slash:comments><pubDate>Fri, 18 Aug 2023 16:43:47 +0300</pubDate></item>
        <item><title><![CDATA[Foto: Policija meklē pērn Mārupē nelegāli nocirstā dižozola 'slepkavas']]></title><category>Kriminālziņas</category><enclosure url="http://g.delfi.lv/images/pix/420x0/lXKF1-RISAE/valsts-policija-aicina-atsaukties-ikvienu-kurs-atpazist-attelos-redzam-55859164.jpg" type="image/png" /><link>https://www.delfi.lv/news/national/criminal/foto-policija-mekle-pern-marupe-nelegali-nocirsta-dizozola-slepkavas.d?id=55858936</link><guid>https://www.delfi.lv/news/national/criminal/foto-policija-mekle-pern-marupe-nelegali-nocirsta-dizozola-slepkavas.d?id=55858936</guid><description><![CDATA[Valsts policija (VP) izplatījusi foto attēlus, kuros redzami vīrieši, kurus likumsargi meklē saistībā ar pērn Mārupē nelikumīgi nocirsto dižozolu, portāls &quot;Delfi&quot; uzzināja VP.]]></description><media:content url="http://g.delfi.lv/images/pix/420x0/lXKF1-RISAE/valsts-policija-aicina-atsaukties-ikvienu-kurs-atpazist-attelos-redzam-55859164.jpg" /><slash:comments>3</slash:comments><pubDate>Fri, 18 Aug 2023 16:42:37 +0300</pubDate></item>
        <item><title><![CDATA[#94 Startup pieredzes stāsts]]></title><category>Tirgziņu Tērzes</category><enclosure url="http://g.delfi.lv/images/pix/420x0/WwAPt6VZ5-A/tirgzinu-terzes-podkasts-jauns-54606568.jpg" type="image/png" /><link>https://www.delfi.lv/podkasti/tirgzinu-terzes/94-startup-pieredzes-stasts.d?id=55858876</link><guid>https://www.delfi.lv/podkasti/tirgzinu-terzes/94-startup-pieredzes-stasts.d?id=55858876</guid><description><![CDATA[Esiet sveicināti 94. epizodē! Šoreiz runāsim par startup pieredzi.BSMS studijā: Ariels Tabaks - jaunuzņēmuma ASYA līdzdibinātājs, sarunu analīzes platformas Pitch Patterns biznesa attīstības vadītājs un produktu dizaineris.08.08.2023. epizode.]]></description><media:content url="http://g.delfi.lv/images/pix/420x0/WwAPt6VZ5-A/tirgzinu-terzes-podkasts-jauns-54606568.jpg" /><slash:comments>0</slash:comments><pubDate>Fri, 18 Aug 2023 15:40:12 +0300</pubDate></item>
        <item><title><![CDATA[#1 Kultūristi un apkaimisti. Kam nepieciešamas apkaimju biedrības?]]></title><category>'Satori' podkāsts</category><enclosure url="http://g.delfi.lv/images/pix/420x0/2A2n1WUXvME/satori-podkasts-51778507.jpg" type="image/png" /><link>https://www.delfi.lv/podkasti/satori-podkasts/1-kulturisti-un-apkaimisti-kam-nepieciesamas-apkaimju-biedribas.d?id=55858846</link><guid>https://www.delfi.lv/podkasti/satori-podkasts/1-kulturisti-un-apkaimisti-kam-nepieciesamas-apkaimju-biedribas.d?id=55858846</guid><description><![CDATA[Šajā epizodē ar raidījuma vadītājiem, Antoniju Skopu un Žulijenu Nuhumu Kulibali, tiekas Sandra Feldmane, Rīgas Apkaimju alianses un Čiekurkalna attīstības biedrības valdes locekle. Sarunāsimies par to, kādi impulsi ļauj apkaimes iedzīvotājiem sanākt kopā biedrībā, par to, vai ideālus nevar iznīcināt resursu trūkums, un vērtīsim skatu uz veidiem, kā savām idejām gūt arī negaidītus sabiedrotos.Biedrības &quot;Ascendum&quot; veidotais raidieraksts &quot;Kultūristi un apkaimisti&quot; ir platforma, kurā ar Rīgas apkaimju biedrību pārstāvjiem un kultūras veidotājiem runāsim par veidiem, kādos iedzīvotāji var pašorganizēties, iesaistīties kopienas dzīvē un padarīt apkaimju dzīvi patīkamāku, tostarp, ar kultūras rīkiem.Raidieraksta tapšanu finansiāli atbalsta Sabiedrības integrācijas fonds no Kultūras ministrijas piešķirtajiem Latvijas valsts budžeta līdzekļiem.10.08.2023. epizode.]]></description><media:content url="http://g.delfi.lv/images/pix/420x0/2A2n1WUXvME/satori-podkasts-51778507.jpg" /><slash:comments>0</slash:comments><pubDate>Fri, 18 Aug 2023 15:37:42 +0300</pubDate></item>
        <item><title><![CDATA[Noskaidroti visi Balvu kautiņa dalībnieki]]></title><category>Kriminālziņas</category><enclosure url="http://g.delfi.lv/images/pix/420x0/Ku3JD5A1f9k/kautinsdure-44674886.jpg" type="image/png" /><link>https://www.delfi.lv/news/national/criminal/noskaidroti-visi-balvu-kautina-dalibnieki.d?id=55858774</link><guid>https://www.delfi.lv/news/national/criminal/noskaidroti-visi-balvu-kautina-dalibnieki.d?id=55858774</guid><description><![CDATA[Valsts policija (VP) noskaidrojusi visus cilvēkus, kuri bija iesaistīti 13. augustā Balvos notikušajā kautiņā, kurā cieta divas personas, portāls &quot;Delfi&quot; uzzināja VP.]]></description><media:content url="http://g.delfi.lv/images/pix/420x0/Ku3JD5A1f9k/kautinsdure-44674886.jpg" /><slash:comments>0</slash:comments><pubDate>Fri, 18 Aug 2023 15:28:26 +0300</pubDate></item>
        <item><title><![CDATA[Stoltenbergs: Ukraina pati izlems, kad būs piemēroti apstākļi miera sarunām]]></title><category>Ārzemēs</category><enclosure url="http://g.delfi.lv/images/pix/420x0/R0dNmE14ugc/stoltenbergs-zelenskis-55449526.jpg" type="image/png" /><link>https://www.delfi.lv/news/arzemes/stoltenbergs-ukraina-pati-izlems-kad-bus-piemeroti-apstakli-miera-sarunam.d?id=55858684</link><guid>https://www.delfi.lv/news/arzemes/stoltenbergs-ukraina-pati-izlems-kad-bus-piemeroti-apstakli-miera-sarunam.d?id=55858684</guid><description><![CDATA[Ceturtdien, 17. augustā, NATO ģenerālsekretārs Jenss Stoltenbergs komentēja, ka Kijivai vienai ir jāizlemj, kad būs piemēroti apstākļi, lai uzsāktu jebkādas sarunas par mieru pēc Krievijas iebrukuma Ukrainā, vēsta aģentūra &quot;Reuters&quot;.]]></description><media:content url="http://g.delfi.lv/images/pix/420x0/R0dNmE14ugc/stoltenbergs-zelenskis-55449526.jpg" /><slash:comments>4</slash:comments><pubDate>Fri, 18 Aug 2023 15:23:35 +0300</pubDate></item>
        <item><title><![CDATA[Foto: Būvdarbi uz Vidzemes šosejas no Melturiem līdz Rīdzenei]]></title><category>Ziņas</category><enclosure url="http://g.delfi.lv/images/pix/420x0/MLXmMIpvf3U/buvdarbi-uz-vidzemes-sosejas-no-melturiem-lidz-ridzenei-20-55858116.jpg" type="image/png" /><link>https://www.delfi.lv/auto/zinas/foto-buvdarbi-uz-vidzemes-sosejas-no-melturiem-lidz-ridzenei.d?id=55858048</link><guid>https://www.delfi.lv/auto/zinas/foto-buvdarbi-uz-vidzemes-sosejas-no-melturiem-lidz-ridzenei.d?id=55858048</guid><description><![CDATA[Turpinās plaši būvdarbi uz Vidzemes šosejas (A2) no Melturiem, pagrieziena uz Cēsīm (P20) līdz Rīdzenei (77,24.–88,10. km). Posma pārbūvi sāka šā gada jūnijā, to plānots pabeigt 2024. gada rudenī, informē &quot;Latvijas Valsts ceļi&quot;.]]></description><media:content url="http://g.delfi.lv/images/pix/420x0/MLXmMIpvf3U/buvdarbi-uz-vidzemes-sosejas-no-melturiem-lidz-ridzenei-20-55858116.jpg" /><slash:comments>0</slash:comments><pubDate>Fri, 18 Aug 2023 14:37:18 +0300</pubDate></item>
        <item><title><![CDATA[Little bits #42: YouTube krāpjas, AI melo, digitālā reklāma zeļ]]></title><category>Little Bits</category><enclosure url="http://g.delfi.lv/images/pix/420x0/6ygQ-HbC83k/little-bits-podkasts-51626897.jpg" type="image/png" /><link>https://www.delfi.lv/podkasti/little-bits/little-bits-42-youtube-krapjas-ai-melo-digitala-reklama-zel.d?id=55857916</link><guid>https://www.delfi.lv/podkasti/little-bits/little-bits-42-youtube-krapjas-ai-melo-digitala-reklama-zel.d?id=55857916</guid><description><![CDATA[Pēc ilgas neredzēšanās mikrofonu ielenkumā iztaujājām un melos pieķērām Google AI &quot;Bārdu&quot;, aprunājām ziņas par YouTube reklāmas tumšo pavēderi, kā arī ieskatījāmies IPA jaunākajā pētījumā &quot;The 3rd Age of Effectiveness&quot; par digitālo reklāmu.11.08.2023. epizode.]]></description><media:content url="http://g.delfi.lv/images/pix/420x0/6ygQ-HbC83k/little-bits-podkasts-51626897.jpg" /><slash:comments>0</slash:comments><pubDate>Fri, 18 Aug 2023 14:33:23 +0300</pubDate></item>
        <item><title><![CDATA[S04E246: Ieva Rosne]]></title><category>Diena pēc</category><enclosure url="http://g.delfi.lv/images/pix/420x0/6IgPVTFhd_s/diena-pec-podkasts-51801193.jpg" type="image/png" /><link>https://www.delfi.lv/podkasti/diena-pec/s04e246-ieva-rosne.d?id=55857852</link><guid>https://www.delfi.lv/podkasti/diena-pec/s04e246-ieva-rosne.d?id=55857852</guid><description><![CDATA[Latvijā ir vairāk nekā 30 000 cilvēku ar īpašām vajadzībām, no kuriem nodarbināti ir salīdzinoši maza daļa. Lai savestu kopā darba devējus un potenciālos darbiniekus, tika izveidota platforma FAVEO. Kā radās ideja par šādu nepieciešamību un vai tā domāta visiem cilvēkiem ar jebkādu invaliditāti? Cik ļoti valsts ir ieinteresēta, lai šie cilvēki pēc iespējas ātrāk atrastu darbu? Atbildes uz šiem jautājumiem uzzināsi, klausoties DIENA PĒC autora Kristapa Pētersona sarunu ar Latvijas Cilvēku ar invaliditāti atbalsta asociācijas dibinātāju Ievu Rosni. Klausies epizodi un dalies!16.08.2023. epizode.]]></description><media:content url="http://g.delfi.lv/images/pix/420x0/6IgPVTFhd_s/diena-pec-podkasts-51801193.jpg" /><slash:comments>0</slash:comments><pubDate>Fri, 18 Aug 2023 14:20:55 +0300</pubDate></item>
        <item><title><![CDATA[S04E245: Jana Trapāne]]></title><category>Diena pēc</category><enclosure url="http://g.delfi.lv/images/pix/420x0/6IgPVTFhd_s/diena-pec-podkasts-51801193.jpg" type="image/png" /><link>https://www.delfi.lv/podkasti/diena-pec/s04e245-jana-trapane.d?id=55857832</link><guid>https://www.delfi.lv/podkasti/diena-pec/s04e245-jana-trapane.d?id=55857832</guid><description><![CDATA[Vides, sociālā un korporatīvā pārvaldība (angliskais saīsinājums - ESG) ieņem arvien būtiskāku lomu uzņēmējdarbībā. IT uzņēmums “Mitigate” ir izveidojis bezmaksas platformu ESG informācijas apkopošanai, kas dod iespēju izmantot datus, saprast problēmas un risināt tās atbildīgi. Lai gan šī pieeja šogad vēl nav obligāta, dažas bankas jau tagad aizņēmējiem pieprasa ESG atskaites, lai izvērtētu kreditēšanas iespēju. Kā caur ilgtspēju mēs varam veicināt uzņēmuma rentabilitāti un vai ar ilgtspēju ir jāpelna? Vai izglītība un skolēnu izglītošana ir ilgtspējas pamats? Par to Eco Baltia valdes priekšsēdētāja Māra Simanoviča sarunā ar “Mitigate” izpilddirektori Janu Trapāni.14.08.2023. epizode.]]></description><media:content url="http://g.delfi.lv/images/pix/420x0/6IgPVTFhd_s/diena-pec-podkasts-51801193.jpg" /><slash:comments>0</slash:comments><pubDate>Fri, 18 Aug 2023 14:15:34 +0300</pubDate></item>
        <item><title><![CDATA[S04E244: Oļegs Krasnopjorovs]]></title><category>Diena pēc</category><enclosure url="http://g.delfi.lv/images/pix/420x0/6IgPVTFhd_s/diena-pec-podkasts-51801193.jpg" type="image/png" /><link>https://www.delfi.lv/podkasti/diena-pec/s04e244-olegs-krasnopjorovs.d?id=55857820</link><guid>https://www.delfi.lv/podkasti/diena-pec/s04e244-olegs-krasnopjorovs.d?id=55857820</guid><description><![CDATA[Laika gaitā, augot ienākumu līmenim, vidējā darba slodze ir samazinājusies un cilvēkiem sāk pieaugt pieprasījums pēc brīvā laika. Kas īsti ir produktivitāte un kā tā ietekmē dažādas jomas? Kā veicināt ekonomisko izaugsmi, ja iedzīvotāju skaits turpina samazināties? Lai sasniegtu attīstīto valstu līmeni, vai mums jāpāriet uz sešu dienu darba nedēļu? Uz šiem un citiem jautājumiem sarunā ar &quot;Accenture&quot; vadītāju Maksimu Jegorovu atbild Latvijas Bankas Monetārās politikas pārvaldes Makroekonomikas analīzes daļas galvenais ekonomists, Latvijas Universitātes docents Oļegs Krasnopjorovs.07.08.2023. epizode.]]></description><media:content url="http://g.delfi.lv/images/pix/420x0/6IgPVTFhd_s/diena-pec-podkasts-51801193.jpg" /><slash:comments>0</slash:comments><pubDate>Fri, 18 Aug 2023 14:13:07 +0300</pubDate></item>
        <item><title><![CDATA[Divi cilvēki aizturēti par pakomātu apzagšanu Rīgā]]></title><category>Kriminālziņas</category><enclosure url="http://g.delfi.lv/images/pix/420x0/CTEtOLkRakw/omniva-pakomats-52148209.jpg" type="image/png" /><link>https://www.delfi.lv/news/national/criminal/divi-cilveki-aiztureti-par-pakomatu-apzagsanu-riga.d?id=55857784</link><guid>https://www.delfi.lv/news/national/criminal/divi-cilveki-aiztureti-par-pakomatu-apzagsanu-riga.d?id=55857784</guid><description><![CDATA[Valsts policija (VP) aizturējusi divas personas, kas tiek turētas aizdomās par vairāku &quot;Omniva&quot; pakomātu apzagšanu Rīgā šī gada jūnijā, portāls &quot;Delfi&quot; uzzināja VP.]]></description><media:content url="http://g.delfi.lv/images/pix/420x0/CTEtOLkRakw/omniva-pakomats-52148209.jpg" /><slash:comments>0</slash:comments><pubDate>Fri, 18 Aug 2023 14:10:40 +0300</pubDate></item>
        <item><title><![CDATA[VDD aizturējis 'Baltijas antifašistu' – taksistu – par spiegošanu Krievijas labā]]></title><category>Kriminālziņas</category><enclosure url="http://g.delfi.lv/images/pix/420x0/c1AvF0iPrFE/taksometrs-taksis-taxi-51861409.jpg" type="image/png" /><link>https://www.delfi.lv/news/national/criminal/vdd-aizturejis-baltijas-antifasistu-taksistu-par-spiegosanu-krievijas-laba.d?id=55857614</link><guid>https://www.delfi.lv/news/national/criminal/vdd-aizturejis-baltijas-antifasistu-taksistu-par-spiegosanu-krievijas-laba.d?id=55857614</guid><description><![CDATA[Turpinot izmeklēt platformā &quot;Telegram&quot; pretvalstiskas aktivitātes izvērsušās noziedzīgās organizācijas &quot;Baltijas antifašisti&quot; darbību, Valsts drošības dienesta (VDD) uzmanībā ir nonācis Latvijas pilsonis, kurš sistemātiski un mērķtiecīgi vācis un organizācijas dalībniekiem nodevis pret Latvijas nacionālās drošības interesēm izmantojamu informāciju par notiekošo Latvijā, portāls &quot;Delfi&quot; uzzināja dienestā.]]></description><media:content url="http://g.delfi.lv/images/pix/420x0/c1AvF0iPrFE/taksometrs-taksis-taxi-51861409.jpg" /><slash:comments>12</slash:comments><pubDate>Fri, 18 Aug 2023 13:49:05 +0300</pubDate></item>
        <item><title><![CDATA[Gangsteru apšaudēs Marseļā šogad dzīvību zaudējuši desmitiem cilvēku]]></title><category>Ārzemēs</category><enclosure url="http://g.delfi.lv/images/pix/420x0/VETaXfcdPJQ/marsela-55857590.jpg" type="image/png" /><link>https://www.delfi.lv/news/arzemes/gangsteru-apsaudes-marsela-sogad-dzivibu-zaudejusi-desmitiem-cilveku.d?id=55857576</link><guid>https://www.delfi.lv/news/arzemes/gangsteru-apsaudes-marsela-sogad-dzivibu-zaudejusi-desmitiem-cilveku.d?id=55857576</guid><description><![CDATA[Divu narkotiku bandu sāncensība Marseļā šogad uzbrukumos, kurus dažkārt sarīko pusaudži, ir nogalinājusi desmitiem cilvēku, ziņo policija, uz kuras teikto atsaucas &quot;Al Jazeera&quot;.]]></description><media:content url="http://g.delfi.lv/images/pix/420x0/VETaXfcdPJQ/marsela-55857590.jpg" /><slash:comments>0</slash:comments><pubDate>Fri, 18 Aug 2023 13:41:11 +0300</pubDate></item>
        <item><title><![CDATA[Foto: Tenerifē postošo savvaļas ugunsgrēku dēļ evakuēti vairāki tūkstoši cilvēku]]></title><category>Ārzemēs</category><enclosure url="http://g.delfi.lv/images/pix/420x0/2uYDY4LTuNY/47rs230817a368-55857430.jpg" type="image/png" /><link>https://www.delfi.lv/news/arzemes/foto-tenerife-postoso-savvalas-ugunsgreku-del-evakueti-vairaki-tukstosi-cilveku.d?id=55857322</link><guid>https://www.delfi.lv/news/arzemes/foto-tenerife-postoso-savvalas-ugunsgreku-del-evakueti-vairaki-tukstosi-cilveku.d?id=55857322</guid><description><![CDATA[Populārajā Spānijas tūristu galamērķī Tenerifē kopš trešdienas, 16. augusta, plosās savvaļas ugunsgrēki. Ceturtdien varasiestādes ziņoja, ka līdz šim evakuēti vairāk nekā 3000 cilvēku, vēsta medijs CNN.]]></description><media:content url="http://g.delfi.lv/images/pix/420x0/2uYDY4LTuNY/47rs230817a368-55857430.jpg" /><slash:comments>0</slash:comments><pubDate>Fri, 18 Aug 2023 13:26:08 +0300</pubDate></item>
        <item><title><![CDATA[KNAB soda bijušo Ogres muzeja direktori par vīra prēmēšanu]]></title><category>Sabiedrība</category><enclosure url="http://g.delfi.lv/images/pix/420x0/6r9bYP_6yJQ/evija-smiltniece-55857328.jpg" type="image/png" /><link>https://www.delfi.lv/news/national/politics/knab-soda-bijuso-ogres-muzeja-direktori-par-vira-premesanu.d?id=55857302</link><guid>https://www.delfi.lv/news/national/politics/knab-soda-bijuso-ogres-muzeja-direktori-par-vira-premesanu.d?id=55857302</guid><description><![CDATA[Izvērtējot toreizējās Ogres Vēstures un mākslas muzeja direktores Evijas Smiltnieces darbības atbilstību likuma normām, Korupcijas novēršanas un apkarošanas birojs (KNAB) valsts amatpersonas rīcībā konstatējis interešu konfliktu, informēja KNAB.]]></description><media:content url="http://g.delfi.lv/images/pix/420x0/6r9bYP_6yJQ/evija-smiltniece-55857328.jpg" /><slash:comments>4</slash:comments><pubDate>Fri, 18 Aug 2023 13:08:18 +0300</pubDate></item>
        <item><title><![CDATA['Viņš aiz sevis atstāja vilšanos' – Neimārs otro reizi šokē futbola pasauli]]></title><category>Sports</category><enclosure url="http://g.delfi.lv/images/pix/420x0/Nhmw_Kq94GE/neimars-futbols-55856864.jpg" type="image/png" /><link>https://www.delfi.lv/delfi-plus/sports/vins-aiz-sevis-atstaja-vilsanos-neimars-otro-reizi-soke-futbola-pasauli.d?id=55855054</link><guid>https://www.delfi.lv/delfi-plus/sports/vins-aiz-sevis-atstaja-vilsanos-neimars-otro-reizi-soke-futbola-pasauli.d?id=55855054</guid><description><![CDATA[Šāds solis izraisīja šoku visā futbola pasaulē - brazīliešu superzvaigzne Neimārs šonedēļ oficiāli kļuva par Āzijas titulētākā kluba &quot;Al Hilal&quot; spēlētāju. Tuvāko divu gadu laikā viņš nopelnīs milzīgu naudu, kas tik un tā atpaliek no iespaidīgā algas čeka, ko saņem turpat Saūda Arābijā spēlējošais Krištianu Ronaldu. Tomēr nauda neesot bijis galvenais iemesls, kāpēc Neimārs nolēmis pamest elites futbolu...]]></description><media:content url="http://g.delfi.lv/images/pix/420x0/Nhmw_Kq94GE/neimars-futbols-55856864.jpg" /><slash:comments>1</slash:comments><pubDate>Fri, 18 Aug 2023 13:03:52 +0300</pubDate></item>
    </channel>
</rss>
XML;
    }
}
